# Generated by Django 4.2.5 on 2023-11-11 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing_list", "0003_alter_client_options_alter_client_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailinglistmessage",
            old_name="created",
            new_name="created_time",
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="created",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="создана",
            ),
        ),
    ]
