# Generated by Django 4.2.5 on 2023-11-11 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "mailing_list",
            "0004_rename_created_mailinglistmessage_created_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglistmessage",
            name="created",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="создана",
            ),
        ),
    ]
